[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && python setup_demo.py; gunicorn hospital_management.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/login/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
